# Generated by Django 6.0.6 on 2026-06-19 05:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Firstname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Z a-z]+$')])),
                ('Lastname', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Z a-z]+$')])),
                ('DOB', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}$', 'Enter 10 digits')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField()),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('monthsalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('working_days', models.IntegerField(default=30)),
                ('absent_days', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.position'),
        ),
    ]
