# Generated by Django 6.0.6 on 2026-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0002_payroll_ot_amount_payroll_payroll_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Permanet', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=20),
        ),
    ]
