# Generated by Django 6.0.6 on 2026-07-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0003_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_deductions', to='Payrollmang.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_earnings', to='Payrollmang.payroll')),
            ],
        ),
    ]
