# Generated by Django 6.0.6 on 2026-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0004_weeklydeduction_weeklyearning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyearning',
            name='payroll',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_type',
            field=models.CharField(choices=[('Monthly', 'Monthly')], default='Monthly', max_length=10),
        ),
        migrations.DeleteModel(
            name='WeeklyDeduction',
        ),
        migrations.DeleteModel(
            name='WeeklyEarning',
        ),
    ]
