# Generated by Django 6.0.6 on 2026-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0005_remove_weeklyearning_payroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(default='Permanent', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_type',
            field=models.CharField(default='Monthly', max_length=10),
        ),
    ]
