# Generated by Django 6.0.6 on 2026-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0006_alter_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='payroll_type',
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekly_deductions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekly_earnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
