# Generated by Django 6.0.6 on 2026-07-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0007_remove_payroll_payroll_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='weekly_deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='weekly_earnings',
        ),
    ]
