# Generated by Django 6.0.6 on 2026-07-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0008_remove_payroll_weekly_deductions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.CreateModel(
            name='WeeklyPayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_entries', to='Payrollmang.payroll')),
            ],
        ),
    ]
