# Generated by Django 6.0.6 on 2026-07-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0009_remove_employee_employee_type_weeklypayrollentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyPayrollEntry',
        ),
    ]
