# Generated by Django 6.0.6 on 2026-07-07 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0010_delete_weeklypayrollentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.employee')),
            ],
            options={
                'verbose_name': 'Weekly Payroll',
                'verbose_name_plural': 'Weekly Payrolls',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], default='Earning', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Payrollmang.weeklypayroll')),
            ],
            options={
                'verbose_name': 'Weekly Payroll Item',
                'verbose_name_plural': 'Weekly Payroll Items',
            },
        ),
    ]
