# Generated by Django 6.0.6 on 2026-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0015_employee_employee_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayrollitem',
            name='hp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayrollitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
