# Generated by Django 6.0.6 on 2026-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0016_weeklypayrollitem_hp_weeklypayrollitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayroll',
            name='description',
            field=models.CharField(blank=True, help_text='Optional remarks', max_length=255),
        ),
    ]
