# Generated by Django 6.0.6 on 2026-07-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0017_weeklypayroll_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklypayroll',
            options={'ordering': ['-week_start'], 'verbose_name': 'Weekly Payroll', 'verbose_name_plural': 'Weekly Payrolls'},
        ),
        migrations.AlterModelOptions(
            name='weeklypayrollitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='weeklypayroll',
            name='unique_employee_week_range',
        ),
        migrations.AddField(
            model_name='weeklypayroll',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weeklypayroll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklypayroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_payrolls', to='Payrollmang.employee'),
        ),
        migrations.AlterField(
            model_name='weeklypayrollitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='weeklypayrollitem',
            name='type',
            field=models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], default='Earning', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='weeklypayroll',
            constraint=models.UniqueConstraint(fields=('employee', 'week_start', 'week_end'), name='unique_employee_weekly_payroll'),
        ),
    ]
