# Generated by Django 6.0.6 on 2026-07-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payrollmang', '0019_alter_employee_department_alter_employee_monthsalary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name': 'Monthly Payroll', 'verbose_name_plural': 'Monthly Payroll'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='weeklypayroll',
            options={'ordering': ['-week_start'], 'verbose_name': 'Weekly Payroll', 'verbose_name_plural': 'Weekly Payroll'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthsalary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payrollmang.position'),
        ),
        migrations.AlterField(
            model_name='weeklypayroll',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
